### PR TITLE
thank you to @gfredericks for pointing out the lame

### PR DESCRIPTION
**Pull request by zeeshanlakhani**

### CODE REVIEW

**Comment by gfredericks** [comment]
I think you can keep using the `or` to do what you added the `if-let` to do -- looks like in the new version the `or` is now superfluous?

**Comment by gfredericks** [comment]
I.e., I would change it to `(or (schema->gen* e) (throw ...))`

**Comment by zeeshanlakhani** [comment]
@gfredericks good point.

**Comment by zeeshanlakhani** [comment]
@gfredericks times when you forget that upside-down carat means or. *pretty symbols*.

**Comment by gfredericks** [comment]
oh no now the indentation is off :astonished:

**Comment by zeeshanlakhani** [comment]
@gfredericks hmm, emacs mode is telling me otherwise, hmm.

**Comment by zeeshanlakhani** [comment]
ah. turned of pretty symbols. derpy derp.

**Comment by gfredericks** [comment]
what did you tell your emacs to rewrite "or" as "^"?

you monster

**Comment by gfredericks** [comment]
Now the two args to `ex-info` aren't lined up

**Comment by zeeshanlakhani** [comment]
@gfredericks i am... yeah fixing now. cold hands.

**Comment by gfredericks** [comment]
did you tell emacs to rewrite `ex-info` as `cold-hands`?

**Comment by zeeshanlakhani** [comment]
If only Github knew how great "^" is.

**Comment by zeeshanlakhani** [comment]
@gfredericks if you're `cold hands cool` i'll merge and make a new point version w/ test.chuck.

**Comment by zeeshanlakhani** [comment]
@gfredericks tho... should use type instead of class.

**Comment by gfredericks** [comment]
w00t :+1:

also :+1: for new release; we've been using fork releases for a while

**Comment by zeeshanlakhani** [comment]
@gfredericks done!.

**Pull request merged**
